;;; gited-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gited.el

(autoload 'gited-list-branches "gited" "\
List all branches or tags for the current repository.
Optional arg PATTERN if non-nil, then must be \"local\", \"remote\",
 or \"tags\".  That lists local branches, remote branches and tags,
 respectively.  When PATTERN is nil, then list the local branches.
Optional arg OTHER-WINDOW means to display the Gited buffer in another window.
Optional arg UPDATE if non-nil, then force to update the gited buffer.
 Otherwise, just switch to the Gited buffer if already exists.
When called interactively prompt for PATTERN.
When called interactively with a prefix set OTHER-WINDOW non-nil.

(fn &optional PATTERN OTHER-WINDOW UPDATE)" t)
(defalias 'gited-list 'gited-list-branches)
(register-definition-prefixes "gited" '("gited-"))


;;; Generated autoloads from gited-ci.el

(register-definition-prefixes "gited-ci" '("gited-"))


;;; Generated autoloads from gited-tests.el

(register-definition-prefixes "gited-tests" '("gited-" "with-"))

;;; End of scraped data

(provide 'gited-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gited-autoloads.el ends here
