(source gnu)
(source melpa)

(package-file "pdf-tools.el")

(files "*.el"
       "README"
       "server/epdfinfo"
       "server/epdfinfo.exe")

(development
 (depends-on "ert-runner")
 (depends-on "undercover"))
