;;; perl-doc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from perl-doc.el

(autoload 'perl-doc "perl-doc" "\
Get Perl documentation like the perldoc command.
Does better formatting than man pages, including hyperlinks.

(fn WORD &optional SECTION)" t)
(autoload 'perl-doc-function "perl-doc" "\
Get Perl documentation for a builtin function WORD.
This retrieves the corresponding section from the perlfunc page.
No completion is done (yet).  Sorry.

(fn TOPIC)" t)
(autoload 'perl-doc-variable "perl-doc" "\
Get Perl documentation for a builtin function WORD.
This retrieves the corresponding section from the perlfunc page.
No completion is done (yet).  Sorry.

(fn TOPIC)" t)
(autoload 'perl-doc-file "perl-doc" "\
Run `perl-doc' on FILE.
This is the same as running `perl-doc' with FILE as an argument,
but provides file-name completion.

(fn FILE)" t)
(register-definition-prefixes "perl-doc" '("directory-files-no-dot-files-regexp" "imenu-create-index-function" "perl-doc-" "speedbar-last-selected-file"))

;;; End of scraped data

(provide 'perl-doc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; perl-doc-autoloads.el ends here
