;;; spell-fu-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from spell-fu.el

(autoload 'spell-fu-mode "spell-fu" "\
Toggle variable `spell-fu-mode' in the current buffer.

This is a minor mode.  If called interactively, toggle the
`Spell-Fu mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `spell-fu-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-spell-fu-mode 'globalized-minor-mode t)
(defvar global-spell-fu-mode nil "\
Non-nil if Global Spell-Fu mode is enabled.
See the `global-spell-fu-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-spell-fu-mode'.")
(custom-autoload 'global-spell-fu-mode "spell-fu" nil)
(autoload 'global-spell-fu-mode "spell-fu" "\
Toggle Spell-Fu mode in all buffers.
With prefix ARG, enable Global Spell-Fu mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Spell-Fu mode is enabled in all buffers where `spell-fu-mode-turn-on'
would do it.

See `spell-fu-mode' for more information on Spell-Fu mode.

(fn &optional ARG)" t)
(register-definition-prefixes "spell-fu" '("spell-fu-"))

;;; End of scraped data

(provide 'spell-fu-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; spell-fu-autoloads.el ends here
